name: Build ZLT APK FINAL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repo
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Java (Required for Android Build)
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Fix Gradle Permission (IMPORTANT)
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Build APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      # Upload APK Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ZLT-FINAL-APK
          path: app/build/outputs/apk/debug/*.apk
